INSERT INTO Estado (sigla, descricao) VALUES('AC','Acre'); 
INSERT INTO Estado (sigla, descricao) VALUES('AL','Alagoas');
INSERT INTO Estado (sigla, descricao) VALUES('AM','Amazonas'); 
INSERT INTO Estado (sigla, descricao) VALUES('AP','Amapá');
INSERT INTO Estado (sigla, descricao) VALUES('BA','Bahia');
INSERT INTO Estado (sigla, descricao) VALUES('CE','Ceará'); 
INSERT INTO Estado (sigla, descricao) VALUES('DF','Distrito Federal');
INSERT INTO Estado (sigla, descricao) VALUES('ES','Espírito Santo');
INSERT INTO Estado (sigla, descricao) VALUES('GO','Goiás');
INSERT INTO Estado (sigla, descricao) VALUES('MA','Maranhão'); 
INSERT INTO Estado (sigla, descricao) VALUES('MG','Minas Gerais');
INSERT INTO Estado (sigla, descricao) VALUES('MS','Mato Grosso do Sul');
INSERT INTO Estado (sigla, descricao) VALUES('MT','Mato Grosso');
INSERT INTO Estado (sigla, descricao) VALUES('PA','Pará');
INSERT INTO Estado (sigla, descricao) VALUES('PB','Paraíba'); 
INSERT INTO Estado (sigla, descricao) VALUES('PE','Pernambuco'); 
INSERT INTO Estado (sigla, descricao) VALUES('PI','Piauí'); 
INSERT INTO Estado (sigla, descricao) VALUES('PR','Paraná');
INSERT INTO Estado (sigla, descricao) VALUES('RJ','Rio de Janeiro');
INSERT INTO Estado (sigla, descricao) VALUES('RN','Rio Grande do Norte');
INSERT INTO Estado (sigla, descricao) VALUES('RO','Rondônia');
INSERT INTO Estado (sigla, descricao) VALUES('RR','Roraima');
INSERT INTO Estado (sigla, descricao) VALUES('RS','Rio Grande do Sul');
INSERT INTO Estado (sigla, descricao) VALUES('SC','Santa Catarina');
INSERT INTO Estado (sigla, descricao) VALUES('SE','Sergipe');
INSERT INTO Estado (sigla, descricao) VALUES('SP','São Paulo');
INSERT INTO Estado (sigla, descricao) VALUES('TO','Tocantins');